### ISSUE TITLE
Instantiation of Honcho

### ISSUE THREAD

**Issue by mkxto** [bizarre/honcho#9]
Hey, i'm struggling to instantiate honcho to register my commands, I tried look arround Honcho code but can't find anything.
Can you help me ?

**Comment by bizarre** [comment]
You create instances of Honcho using the builder.

```java
Honcho honcho = new Honcho.Builder().build();
```

If you're using Honcho for the Bukkit API then you can install the Bukkit feature into Honcho by specifying the feature in the builder like so:

```java
Honcho honcho = new Honcho.Builder().withFeature(new BukkitFeature(javaPlugin)).build();
```
